/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.vistas;

import com.unab.edu.dao.*;
import com.unab.edu.entidades.Persona;
import com.unab.edu.entidades.Profesor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mauricio
 */
public class crudProfesor extends javax.swing.JFrame {

    /**
     * Creates new form crudProfesor
     */
    public crudProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdProfesor.enable(false);
        MostrarPersonas();
        MostrarProfesores();
    }

    void MostrarPersonas() {
        String TITULOS[] = {"ID", "NOMBREPERSONA"};
        DefaultTableModel ModeloTabla = new DefaultTableModel(null, TITULOS);
        //tbPersona.setModel(ModeloTabla);
        ClsPersona clasePersona = new ClsPersona();

        //ArrayList<Persona> Personas = clasePersona.MostrarPersonas();
        ArrayList<Persona> Personas = clasePersona.MostrarProfesoresSinUsuario();
        //Creamos un array donde volcaremos los datos traidos en MostrarPersona()
        String filas[] = new String[2];
        for (var iterarDatoPersona : Personas) {
            //agregamos cada dato de la consulta en un espacio del arreglo
            filas[0] = String.valueOf(iterarDatoPersona.getIdPersona());
            filas[1] = iterarDatoPersona.getNombre() + " " + iterarDatoPersona.getApellido();
            //Agregamos el arreglo de los datos al modelo de la Tabla
            ModeloTabla.addRow(filas);
        }
        //asignamos el modelo a la Tabla para mostrarlos al usuario
        tbPersonas.setModel(ModeloTabla);
    }

    void MostrarProfesores() {
        String TITULOS[] = {"IDPROFESOR", "IDPERSONA", "NOMBRE", "DUI", "USUARIO", "PASSWORD"};
        DefaultTableModel modeloTabla = new DefaultTableModel(null, TITULOS);
        ClsProfesor profesorDao = new ClsProfesor();
        var listaProfesores = profesorDao.MostrarProfesores();
        String filas[] = new String[6];
        for (var iterarDatos : listaProfesores) {
            filas[0] = String.valueOf(iterarDatos.getId());
            filas[1] = String.valueOf(iterarDatos.getIdPersona());
            filas[2] = iterarDatos.getNombre();
            filas[3] = iterarDatos.getDui();
            filas[4] = iterarDatos.getUsuario();
            filas[5] = iterarDatos.getPass();
            modeloTabla.addRow(filas);
        }
        tbProfesores.setModel(modeloTabla);
    }

    void limpiar() {
        txtIdProfesor.setText("");
        txtIdPersona.setText("");
        txtDui.setText("");
        txtUsuario.setText("");
        txtPass.setText("");
    }
    String passBaseDeDatos = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpMostrar = new javax.swing.JTabbedPane();
        jpDatos = new javax.swing.JPanel();
        txtIdProfesor = new javax.swing.JTextField();
        txtIdPersona = new javax.swing.JTextField();
        txtDui = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPersonas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jpMostrarTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProfesores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpMostrar.setBackground(new java.awt.Color(204, 204, 255));
        tpMostrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jpDatos.setBackground(new java.awt.Color(228, 227, 233));

        txtIdProfesor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtIdPersona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbPersonas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPersonas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selecciona la Persona");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("IDPERSONA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("DUI");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("USUARIO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("PASSWORD");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(txtIdPersona)
                                .addComponent(txtDui)
                                .addComponent(txtUsuario)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(txtIdProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(67, 67, 67))))
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(50, 50, 50)
                        .addComponent(btnEliminar)
                        .addGap(46, 46, 46)
                        .addComponent(btnActualizar)
                        .addGap(47, 47, 47)
                        .addComponent(btnLimpiar)
                        .addContainerGap())))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar)
                    .addComponent(btnLimpiar))
                .addGap(40, 40, 40))
        );

        tpMostrar.addTab("DATOS", jpDatos);

        jpMostrarTabla.setBackground(new java.awt.Color(228, 227, 233));

        tbProfesores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProfesoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbProfesores);

        javax.swing.GroupLayout jpMostrarTablaLayout = new javax.swing.GroupLayout(jpMostrarTabla);
        jpMostrarTabla.setLayout(jpMostrarTablaLayout);
        jpMostrarTablaLayout.setHorizontalGroup(
            jpMostrarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMostrarTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpMostrarTablaLayout.setVerticalGroup(
            jpMostrarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMostrarTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tpMostrar.addTab("MOSTRAR DATOS", jpMostrarTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMostrar)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void tbPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPersonasMouseClicked
        // TODO add your handling code here:
        int fila = tbPersonas.getSelectedRow();
        txtIdPersona.setText(String.valueOf(tbPersonas.getValueAt(fila, 0)));
    }//GEN-LAST:event_tbPersonasMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        ClsProfesor profeDao = new ClsProfesor();
        Profesor prof = new Profesor();
        prof.setIdPersona(Integer.parseInt(txtIdPersona.getText()));
        prof.setDui(txtDui.getText());
        prof.setUsuario(txtUsuario.getText());
        prof.setPass(txtPass.getText());
        profeDao.AgregarProfesor(prof);
        MostrarPersonas();
        MostrarProfesores();
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        ClsProfesor profeDao = new ClsProfesor();
        Profesor profe = new Profesor();
        profe.setId(Integer.parseInt(txtIdProfesor.getText()));
        //Llamamos el metodo para eliminar
        profeDao.EliminarProfesor(profe);
        MostrarPersonas();
        MostrarProfesores();
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        ClsProfesor profeDao = new ClsProfesor();
        Profesor prof = new Profesor();
        prof.setId(Integer.parseInt(txtIdProfesor.getText()));
        prof.setIdPersona(Integer.parseInt(txtIdPersona.getText()));
        prof.setDui(txtDui.getText());
        prof.setUsuario(txtUsuario.getText());
        prof.setPass(txtPass.getText());
        if (passBaseDeDatos.equals(txtPass.getText())) {
            profeDao.ActualizarProfesor(prof, false);
            //JOptionPane.showMessageDialog(null, "Son iguales");
        } else {
            profeDao.ActualizarProfesor(prof, true);
            //JOptionPane.showMessageDialog(null, "Cambiaron");
        }
        MostrarProfesores();
        MostrarPersonas();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tbProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProfesoresMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Si funciona el Evento");
        //Movernos dentro de los elementos del TabbedPane
        tpMostrar.setSelectedIndex(tpMostrar.indexOfComponent(jpDatos));
        //Obtener la fila seleccionada
        int fila = tbProfesores.getSelectedRow();
        //Capturando los datos de la fila seleccionada "IDPROFESOR", "IDPERSONA", "NOMBRE", "USUARIO", "PASSWORD"
        String Id = String.valueOf(tbProfesores.getValueAt(fila, 0));
        String IdPersona = String.valueOf(tbProfesores.getValueAt(fila, 1));
        String Dui = String.valueOf(tbProfesores.getValueAt(fila, 3));
        String Usuario = String.valueOf(tbProfesores.getValueAt(fila, 4));
        String Pass = String.valueOf(tbProfesores.getValueAt(fila, 5));
        //para actualizarla despues
        passBaseDeDatos = String.valueOf(tbProfesores.getValueAt(fila, 5));
        //Asignando los datos capturados al formulario
        txtIdProfesor.setText(Id);
        txtIdPersona.setText(IdPersona);
        txtDui.setText(Dui);
        txtUsuario.setText(Usuario);
        txtPass.setText(Pass);
    }//GEN-LAST:event_tbProfesoresMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpMostrarTabla;
    private javax.swing.JTable tbPersonas;
    private javax.swing.JTable tbProfesores;
    private javax.swing.JTabbedPane tpMostrar;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtIdPersona;
    private javax.swing.JTextField txtIdProfesor;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
